#!/bin/sh
ATTR=sshPublicKey
BASE="$(grep '^[[:space:]]*base[[:space:]]\+passwd' /etc/nslcd.conf | awk '{print $3}')"
LDIF="$(ldapsearch -LLL -x -b "$BASE" "(&(objectClass=posixAccount)(uid=$1))" $ATTR \
	| sed -n '/^ /! { x; s/\n //g; 1!p; }; /^ /H; $ {g; s/\n //g; p; }' | grep "^$ATTR:")"
test -n "$LDIF" || exit 1
if echo "$LDIF" | grep -q "^$ATTR::"; then
	echo "$LDIF" | cut -d ' ' -f 2 | base64 -d
else
	echo "$LDIF" | cut -d ' ' -f 2
fi
